### PR TITLE
Add vendors resource to retsly-schemas

### PR DESCRIPTION
**Pull request by CMClay**

### CODE REVIEW

**Comment by CMClay** [comment]
@MadManMathew @wired8 Review please.

**Comment by wired8** [comment]
:+1:

**Comment by CMClay** [comment]
@MadManMathew review please :)

**Comment by CMClay** [comment]
@MadManMathew ping! Thanks :beers:

**Comment by CMClay** [comment]
@CalvinScott Review please.

**Comment by CalvinScott** [comment]
:+1:

**Pull request merged**
