### PR TITLE
Update fields that should be array of strings instead of a single string

### PR DESCRIPTION
**Pull request by MadManMathew**
When we added new values to our retsly-schemas they were all added as strings but were actually arrays ( arrays are nicer) 
 - may need matching import issue

### CODE REVIEW

**Comment by MadManMathew** [comment]
@CMClay @CalvinScott  review please. We will need to tag a new release and update import version for it to take effect

**Comment by CMClay** [comment]
:+1:

**Comment by CMClay** [comment]
@CalvinScott lets get this in so we can tag a new release.

**Comment by CalvinScott** [comment]
Sorry didn't even see I was tagged; are you sure YearBuiltDetails is an array? Where I see it in the omreb data it doesn't look like it. The rest look good :+1:

**Comment by CMClay** [comment]
@MadManMathew I think @CalvinScott is right about `YearBuiltDetails'.

**Comment by MadManMathew** [comment]
I will also update frontageLength as it is a string

**Comment by MadManMathew** [comment]
@CMClay quick re-review?

**Comment by CMClay** [comment]
:+1:

**Pull request merged**
