### PR TITLE
Add new agent/office fields to listing schema

### PR DESCRIPTION
**Pull request by Jkhwan**
## Team

- @jkhwan
- @kregensberg 
- @EnFinlay 
- @CalvinScott 

## Overview

As requested by Dotloop, adding the agent name and office name onto the listings would allow them to reduce the number of api requests.

## Tasks

- [x] Add seven new fields

## Release

These changes are minor.

### CODE REVIEW

**Comment by Jkhwan** [comment]
@lvivier @switters review please

**Comment by switters** [comment]
👍 except for the descriptions of the new fields -- I feel like we're insulting the intelligence of our users.

**Comment by lvivier** [comment]
:+1: Do the field descriptions for this repo come from the DD or do we make 'em up?

**Comment by Jkhwan** [comment]
@switters free feel to come up with more obscure descriptions, lol
@lvivier I have no idea, i just copied it from the agents description file.

**Pull request merged**
