### PR TITLE
Add buyerFinancing field to retsly schemas

### PR DESCRIPTION
**Pull request by CMClay**
## Overview
Add buyerFinancing field to retsly schemas

### CODE REVIEW

**Comment by CMClay** [comment]
@MadManMathew @lvivier Quick review please.

**Comment by MadManMathew** [comment]
:+1:  is there an associated reso mapping issue in import

**Comment by CMClay** [comment]
@lvivier will add the mapping on retsly/import.

**Comment by lvivier** [comment]
:+1:

**Pull request merged**
