### PR TITLE
Listing ddMap Typo

### PR DESCRIPTION
**Pull request by CalvinScott**
# Overview

While working on improving RESO test data on the API, I noticed that there seems to be a typo on the listing ddMap object.

```
  purchaseContractDate: 'OriginalEntryTimestamp',
  originalEntryTimestamp: {type: 'date'},

  taxAssessedValue: 'TaxAssessedValue',
```

To my eyes, it looks like originalEntryTimestamp should just be 'OriginalEntryTimestamp' and purchaseContractDate should be 'PurchaseContractDate' (presumably).

# Tasks

- [x] Update the two fields accordingly

# Deployment

Release as **_patch_**

(Tentative - taken from another retsly-schemas issue)
- npm install and restart api
- npm install and build docs www
- npm install and restart import

### CODE REVIEW

**Comment by CalvinScott** [comment]
@lvivier @switters Could I get a review considering @CMClay isn't around?

**Comment by lvivier** [comment]
🎆 👍

**Comment by lvivier** [comment]
This has to go out as a patch release I think for it to get picked up by its various dependents…I can release it or somebody from @Retsly/bravo?

**Comment by switters** [comment]
💯 👍

**Comment by CalvinScott** [comment]
@lvivier 10-4. It is now in the hands of the Data gods.

**Pull request merged**
