### PR TITLE
Add property, member mappings to index.js

### PR DESCRIPTION
**Pull request by switters**
Add property, member mappings to index.js exports.

### CODE REVIEW

**Comment by switters** [comment]
@MadManMathew @lvivier review?

**Comment by lvivier** [comment]
@switters this doesn't look harmful, but context? just for fun? something broken somewhere?

**Comment by slajax** [comment]
ping @switters @lvivier next steps?

**Comment by switters** [comment]
@slajax @lvivier Apologies for the delay -- nothing is broken. These are convenience to make it easier to associate our schemas with datadictionary for the vendor mapping tools I've been working on.

**Comment by lvivier** [comment]
@switters do you need this? if so bring it in and release?

**Comment by switters** [comment]
@lvivier 10-4

**Pull request merged**
