### PR TITLE
Remove emails from response

### PR DESCRIPTION
**Pull request by RongxinZhang**
ref: https://github.com/Retsly/www/issues/706

- [x] Remove emails from Agents

### CODE REVIEW

**Comment by RongxinZhang** [comment]
@CMClay @MadManMathew  please review

**Comment by MadManMathew** [comment]
@slajax are we also worried about cellphone? 
@RongxinZhang I'm pretty sure we need to remove them in the db and write a migration

**Comment by CMClay** [comment]
The email are currently filtered out by the api, but this is also necessary. Make sure to NPM install and rebuild docs after this is published. :+1:

**Comment by slajax** [comment]
@MadManMathew phone numbers are fine as most agents put their brokers number in, we just don't want people farming emails from us for the purpose of marketing their products - we may need to revisit this if we need to support a contact method for the agent, but it would be some level of abstraction where we let them submit it through our leads API. MLSs haven't been concerned with phone numbers as that is a common thing, but emails seem to be a big privacy concern for them, which I anticipated.

**Comment by slajax** [comment]
@RongxinZhang @CMClay we need to make sure all emails, both on Retsly and RESO are filtered out. The logic I added back when, wasn't the best.

**Comment by CMClay** [comment]
@slajax I'll double check the logic on api.

**Comment by RongxinZhang** [comment]
@slajax @CMClay sounds good.

**Pull request merged**
