### PR TITLE
Add status field to listing, agent, and office. 

### PR DESCRIPTION
**Pull request by CMClay**

### CODE REVIEW

**Comment by CMClay** [comment]
@MadManMathew @lvivier @switters Quicky review please.

**Comment by CMClay** [comment]
@lvivier @slajax @MadManMathew  Do you guys think we should support all the DD statuses for listings?:  Active, Backup, Canceled, Closed, Expired, Pending, Withdrawn.

Seems like a bit much. Do you think active/inactive is enough?

**Comment by slajax** [comment]
We absolutely need to support all of them if we expect people to be able to build business ready applications on top of Retsly.

**Comment by CMClay** [comment]
@slajax I don't agree. We disseminate the DD schema into a more concise meaningful retsly schema. We should probably take the same approach with the status enums like this. If we find that vendors use all these statuses in a consistent, meaningful way, then I absolutely agree you. I checked our import data,  there aren't any listings that have statuses other than 'active' and 'pending'.

I'll add the all the DD statuses, but I think it's probably something we should revisit once we get more data.

**Comment by CMClay** [comment]
For now, status will just be a direct map of the relevant DD field. Not using an enum.

**Comment by CMClay** [comment]
@MadManMathew @switters Review please.

**Comment by switters** [comment]
:+1: yis

**Comment by MadManMathew** [comment]
:+1:

**Pull request merged**
