### PR TITLE
Schema changes

### PR DESCRIPTION
**Pull request by CMClay**
#### Overview
ref Retsly/import#229
Add some fields to listings, and any other possible tweaks.

###### For Listings
- [x] ContractStatusChangeDate
- [x] ContingentDate
- [x] WithdrawnDate
- [x] OffMarketDate
- [x] OriginalEntryTimestamp
- [x] PurchaseContractDate

- [x] LastModifiedTimestamp (agent)

- [x] Remove `crud` from vendor

- [x] `clientId` => `clientID` (application)

- [ ] Tag a new release.

#### Deployment
- npm install and restart api
- npm install and build docs www
- npm install and restart import

### CODE REVIEW

**Comment by CMClay** [comment]
@CalvinScott @thalesfsp Review please.

**Comment by thalesfsp** [comment]
:+1: @CalvinScott some typo? Hehehe! ;)

**Comment by CalvinScott** [comment]
@thalesfsp Not today, looks good to me :+1:

**Comment by MadManMathew** [comment]
@CMClay can you take on https://github.com/Retsly/import/issues/247 ? and just include it here?
could you also add lastModified to Member

**Comment by CMClay** [comment]
@MadManMathew We have dateSold. I don't want to include any renaming fields in this PR. lastModified is there on Member.

**Pull request merged**
